version: '3'
services:
  postgres:
    image: postgres:13.8
    volumes:
      - .data_db/postgres:/var/lib/postgresql
    env_file:
      - ./.env
    ports:
      - '5432:5432'

networks:
  default:
    name: nest-net
